name: Release Drafter
on:
  push:
    branches:
      - master
jobs:
  update_release_draft:
    name: Update Release Notes Draft
    uses: codehaus-plexus/.github/.github/workflows/release-drafter.yml@v0.0.4
